package practico6.igu;

import static java.awt.image.ImageObserver.WIDTH;
import java.util.TreeSet;
import javax.swing.JOptionPane;
import practico6.logica.Productos;

/**
 *
 * @author marus
 */
public class Menu extends javax.swing.JFrame {

    public static TreeSet<Productos> productos = new TreeSet<>();

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setSize(1000, 600);
        this.setLocationRelativeTo(null);// formulario centrado
        this.setResizable(false);
        this.setTitle("MENU");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAdministracion = new javax.swing.JMenu();
        jbmProducto = new javax.swing.JRadioButtonMenuItem();
        jmConsultas = new javax.swing.JMenu();
        jmiRubro = new javax.swing.JRadioButtonMenuItem();
        jmiNombre = new javax.swing.JRadioButtonMenuItem();
        jmiPrecio = new javax.swing.JRadioButtonMenuItem();
        jmExit = new javax.swing.JMenu();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        escritorio.getAccessibleContext().setAccessibleParent(null);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 540));

        jmAdministracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practico6/imagenes/categorias.png"))); // NOI18N
        jmAdministracion.setText("ADMINISTRACION");
        jmAdministracion.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jmAdministracion.setPreferredSize(new java.awt.Dimension(150, 50));

        jbmProducto.setSelected(true);
        jbmProducto.setText("PRODUCTOS");
        jbmProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmProductoActionPerformed(evt);
            }
        });
        jmAdministracion.add(jbmProducto);

        jMenuBar1.add(jmAdministracion);

        jmConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practico6/imagenes/anadir.png"))); // NOI18N
        jmConsultas.setText("CONSULTAS");
        jmConsultas.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jmConsultas.setPreferredSize(new java.awt.Dimension(150, 50));

        jmiRubro.setSelected(true);
        jmiRubro.setText("RUBRO");
        jmiRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRubroActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiRubro);

        jmiNombre.setSelected(true);
        jmiNombre.setText("NOMBRE");
        jmiNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNombreActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiNombre);

        jmiPrecio.setSelected(true);
        jmiPrecio.setText("PRECIO");
        jmiPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrecioActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiPrecio);

        jMenuBar1.add(jmConsultas);

        jmExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practico6/imagenes/cerrar-sesion.png"))); // NOI18N
        jmExit.setText("SALIR");
        jmExit.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jmExit.setPreferredSize(new java.awt.Dimension(150, 50));

        jRadioButtonMenuItem5.setSelected(true);
        jRadioButtonMenuItem5.setText("EXIT");
        jRadioButtonMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem5ActionPerformed(evt);
            }
        });
        jmExit.add(jRadioButtonMenuItem5);

        jMenuBar1.add(jmExit);
        jmExit.getAccessibleContext().setAccessibleParent(this);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbmProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmProductoActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        GestionProductos nuevo = new GestionProductos();
        nuevo.setVisible(true);
        escritorio.add(nuevo);
        escritorio.moveToFront(nuevo);
    }//GEN-LAST:event_jbmProductoActionPerformed

    private void jmiRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRubroActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        Rubro rub = new Rubro();
        rub.setVisible(true);
        escritorio.add(rub);
        escritorio.moveToFront(rub);
    }//GEN-LAST:event_jmiRubroActionPerformed

    private void jmiNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNombreActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        Nombre nomb = new Nombre();
        nomb.setVisible(true);
        escritorio.add(nomb);
        escritorio.moveToFront(nomb);
    }//GEN-LAST:event_jmiNombreActionPerformed

    private void jmiPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrecioActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        Precio press = new Precio();
        press.setVisible(true);
        escritorio.add(press);
        escritorio.moveToFront(press);
    }//GEN-LAST:event_jmiPrecioActionPerformed

    private void jRadioButtonMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem5ActionPerformed
        JOptionPane.showMessageDialog(this, "SU CARGA HA SIDO EXITOSA");
        Principal salida = new Principal();
        salida.setVisible(true);
        
    }//GEN-LAST:event_jRadioButtonMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JRadioButtonMenuItem jbmProducto;
    private javax.swing.JMenu jmAdministracion;
    private javax.swing.JMenu jmConsultas;
    private javax.swing.JMenu jmExit;
    private javax.swing.JRadioButtonMenuItem jmiNombre;
    private javax.swing.JRadioButtonMenuItem jmiPrecio;
    private javax.swing.JRadioButtonMenuItem jmiRubro;
    // End of variables declaration//GEN-END:variables
}
