
package practico6.igu;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import practico6.logica.Productos;

/**
 *
 * @author marus
 */
public class Nombre extends javax.swing.JInternalFrame {
DefaultTableModel modelo = new DefaultTableModel();
 public boolean isCellEditable (int f, int c){
        return false; // metodo para impedir editar una tabla
    }
    /**
     * Creates new form Nombre
     */
    public Nombre() {
        initComponents();
        this.setSize(800, 525);
        this.setResizable(false);
        this.setTitle("BUSQUEDA POR NOMBRE");
        String ids [] = {"Codigo" , "Descripcion", "Precio", "Stock"};
        modelo.setColumnIdentifiers(ids);
        jtInventario.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpNombre = new javax.swing.JPanel();
        jlNombre = new javax.swing.JLabel();
        jspNombre = new javax.swing.JScrollPane();
        jtInventario = new javax.swing.JTable();
        jlCaracteres = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jbSalir2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jpNombre.setBackground(new java.awt.Color(153, 255, 204));

        jlNombre.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jlNombre.setText("LISTA DE PRODUCTOS POR NOMBRE");

        jtInventario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtInventarioMouseClicked(evt);
            }
        });
        jspNombre.setViewportView(jtInventario);

        jlCaracteres.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jlCaracteres.setText("INGRESE LOS PRIMEROS CARACTERES:");

        jtfNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNombreKeyReleased(evt);
            }
        });

        jbSalir2.setBackground(new java.awt.Color(204, 255, 102));
        jbSalir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practico6/imagenes/cerrar-sesion.png"))); // NOI18N
        jbSalir2.setText("EXIT");
        jbSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalir2ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practico6/imagenes/nuevo-producto.png"))); // NOI18N

        javax.swing.GroupLayout jpNombreLayout = new javax.swing.GroupLayout(jpNombre);
        jpNombre.setLayout(jpNombreLayout);
        jpNombreLayout.setHorizontalGroup(
            jpNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNombreLayout.createSequentialGroup()
                .addGroup(jpNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNombreLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jspNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpNombreLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jbSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNombreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpNombreLayout.createSequentialGroup()
                        .addComponent(jlNombre)
                        .addGap(176, 176, 176))
                    .addGroup(jpNombreLayout.createSequentialGroup()
                        .addComponent(jlCaracteres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148))))
        );
        jpNombreLayout.setVerticalGroup(
            jpNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNombreLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jlNombre)
                .addGroup(jpNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNombreLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jpNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCaracteres)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNombreLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addComponent(jspNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbSalir2)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jbSalir2.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyReleased
      //busco producto por caracteres
      borrarFilas();
        for (Productos generar: Menu.productos ) {
            if (generar.getDescripcion().toLowerCase().startsWith(jtfNombre.getText().toLowerCase())) {
                modelo.addRow(new Object[]{
                generar.getCodigo(),
                generar.getDescripcion(),
                generar.getPrecio(),
                generar.getStock(),
            });
        }
    }//GEN-LAST:event_jtfNombreKeyReleased
    }
    private void jtInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtInventarioMouseClicked
        int filaSeleccionada=jtInventario.getSelectedRow();
        int codigo=(Integer)jtInventario.getValueAt(filaSeleccionada, 0);
        JOptionPane.showMessageDialog(this,"El codigo del producto es : " + codigo);
    }//GEN-LAST:event_jtInventarioMouseClicked

    private void jbSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalir2ActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalir2ActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbSalir2;
    private javax.swing.JLabel jlCaracteres;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JPanel jpNombre;
    private javax.swing.JScrollPane jspNombre;
    private javax.swing.JTable jtInventario;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
private void borrarFilas(){
        int indice = modelo.getRowCount() -1;
        
        for (int i = indice;i>=0;i--){
            modelo.removeRow(i);
        }
    }

}

