
package practico6.igu;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import practico6.logica.Productos;

/**
 *
 * @author marus
 */
public class Precio extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel();// creo mi tabla

    public boolean isCellEditable(int f, int c) {
        return false; // metodo para impedir editar una tabla
    }
    private Productos prodEncontrado = null;

    /**
     * Creates new form Precio
     */
    public Precio() {
        initComponents();
        this.setSize(800, 525);
        this.setResizable(false);
        this.setTitle("BUSQUEDA POR RUBRO");
        String ids[] = {"Codigo", "Descripcion", "Precio", "Stock"};
        modelo.setColumnIdentifiers(ids);
        jtInventario.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPrecio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtInventario = new javax.swing.JTable();
        jbSalir3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfPrecioDesde = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfPrecioHasta = new javax.swing.JTextField();
        jbBuscar2 = new javax.swing.JButton();

        jpPrecio.setBackground(new java.awt.Color(214, 207, 129));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setText("LISTA DE PRODUCTOS POR PRECIO");

        jtInventario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtInventarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtInventario);

        jbSalir3.setBackground(new java.awt.Color(153, 255, 153));
        jbSalir3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practico6/imagenes/cerrar-sesion.png"))); // NOI18N
        jbSalir3.setText("EXIT");
        jbSalir3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbSalir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalir3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setText("ENTRE $ :");

        jtfPrecioDesde.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setText("HASTA");

        jtfPrecioHasta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbBuscar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practico6/imagenes/historial1.png"))); // NOI18N
        jbBuscar2.setText("BUSCAR");
        jbBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPrecioLayout = new javax.swing.GroupLayout(jpPrecio);
        jpPrecio.setLayout(jpPrecioLayout);
        jpPrecioLayout.setHorizontalGroup(
            jpPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrecioLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(jpPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPrecioLayout.createSequentialGroup()
                        .addComponent(jbSalir3, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPrecioLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPrecioLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtfPrecioDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jtfPrecioHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jbBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPrecioLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(183, 183, 183))))
        );
        jpPrecioLayout.setVerticalGroup(
            jpPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrecioLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jpPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfPrecioDesde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPrecioHasta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jbBuscar2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbSalir3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalir3ActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalir3ActionPerformed

    private void jbBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscar2ActionPerformed
        // para buscar producto entre dos variables de precios
         borrarFilas();
        prodEncontrado = null;
        try {
            double precioDesde = Double.parseDouble(jtfPrecioDesde.getText());
            double precioHasta = Double.parseDouble(jtfPrecioHasta.getText());

            for (Productos prod : Menu.productos) {
                double precio = prod.getPrecio();
                if (precio >= precioDesde && precio <= precioHasta) {
                    prodEncontrado = prod;
                    break;
                }
            }
            if (prodEncontrado == null) {
                JOptionPane.showMessageDialog(this, "No se encuentra producto con esos valores");
            } else {
                modelo.addRow(new Object[]{// agrego - imprimo tabla en mi jIF
                    prodEncontrado.getCodigo(),
                    prodEncontrado.getDescripcion(),
                    prodEncontrado.getPrecio(),
                    prodEncontrado.getRubro(),
                    prodEncontrado.getStock(),});
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese valores numéricos válidos para los precios.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbBuscar2ActionPerformed

    private void jtInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtInventarioMouseClicked
        // metodo para hacar clik en una fila y me apareza una ventana emergente con el dato del mismo
         int filaSeleccionada=jtInventario.getSelectedRow();
        double precio=(Integer)jtInventario.getValueAt(filaSeleccionada, 0);
        JOptionPane.showMessageDialog(this,"El precio del producto seleccionado es $ : " + precio);
    }//GEN-LAST:event_jtInventarioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscar2;
    private javax.swing.JButton jbSalir3;
    private javax.swing.JPanel jpPrecio;
    private javax.swing.JTable jtInventario;
    private javax.swing.JTextField jtfPrecioDesde;
    private javax.swing.JTextField jtfPrecioHasta;
    // End of variables declaration//GEN-END:variables
private void borrarFilas(){
        int indice = modelo.getRowCount() -1;
        
        for (int i = indice;i>=0;i--){
            modelo.removeRow(i);
        }
    }

}
