
package practico6.igu;

import javax.swing.table.DefaultTableModel;
import practico6.logica.Categorias;
import practico6.logica.Productos;

/**
 *
 * @author marus
 */
public class Rubro extends javax.swing.JInternalFrame {
DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form Rubro
     */
    public Rubro() {
        initComponents();
        this.setSize(800, 525);
        this.setResizable(false);
        this.setTitle("BUSQUEDA POR RUBRO");
         String ids [] = {"Codigo" , "Descripcion", "Precio", "Stock"};
        modelo.setColumnIdentifiers(ids);
        jtInventario.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpRubro = new javax.swing.JPanel();
        jlListado = new javax.swing.JLabel();
        jlSeleccion = new javax.swing.JLabel();
        jspPanelRubro = new javax.swing.JScrollPane();
        jtInventario = new javax.swing.JTable();
        jlIcon = new javax.swing.JLabel();
        jcbListaRubro = new javax.swing.JComboBox<>();
        jbSalir = new javax.swing.JButton();

        jpRubro.setBackground(new java.awt.Color(255, 255, 153));

        jlListado.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jlListado.setText("LISTADO DE PRODUCTOS POR RUBRO");

        jlSeleccion.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlSeleccion.setText("SELECCIONE RUBRO : ");

        jtInventario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspPanelRubro.setViewportView(jtInventario);

        jlIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practico6/imagenes/icons8-mostrar-propiedad-64.png"))); // NOI18N

        jcbListaRubro.setModel(new javax.swing.DefaultComboBoxModel<>(new Categorias[] { Categorias.COMESTIBLE,Categorias.LIMPIEZA,Categorias.PERFUMERIA }));
        jcbListaRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbListaRubroActionPerformed(evt);
            }
        });

        jbSalir.setBackground(new java.awt.Color(102, 102, 255));
        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practico6/imagenes/cerrar-sesion.png"))); // NOI18N
        jbSalir.setText("EXIT");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpRubroLayout = new javax.swing.GroupLayout(jpRubro);
        jpRubro.setLayout(jpRubroLayout);
        jpRubroLayout.setHorizontalGroup(
            jpRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRubroLayout.createSequentialGroup()
                .addGroup(jpRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRubroLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jlSeleccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbListaRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jlIcon))
                    .addGroup(jpRubroLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jlListado))
                    .addGroup(jpRubroLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jspPanelRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpRubroLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jpRubroLayout.setVerticalGroup(
            jpRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRubroLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jlListado)
                .addGroup(jpRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRubroLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jlIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpRubroLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jpRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcbListaRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlSeleccion))))
                .addGap(18, 18, 18)
                .addComponent(jspPanelRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbSalir)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpRubro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpRubro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpRubro.getAccessibleContext().setAccessibleParent(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbListaRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbListaRubroActionPerformed
       // imprimo en tabla el arrays de producto, segun la categoria
        Categorias mostrar = (Categorias)jcbListaRubro.getSelectedItem();
        borrarFilas();
        for (Productos imprimir: Menu.productos) {
            if (imprimir.getRubro().equals(mostrar)) {
                modelo.addRow(new Object[]{imprimir.getCodigo(),imprimir.getDescripcion(),imprimir.getPrecio(),imprimir.getStock()});
            } 
        }
    }//GEN-LAST:event_jcbListaRubroActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
       dispose(); // se usa cuando tengo que salir de un jinternal frame
    }//GEN-LAST:event_jbSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Categorias> jcbListaRubro;
    private javax.swing.JLabel jlIcon;
    private javax.swing.JLabel jlListado;
    private javax.swing.JLabel jlSeleccion;
    private javax.swing.JPanel jpRubro;
    private javax.swing.JScrollPane jspPanelRubro;
    private javax.swing.JTable jtInventario;
    // End of variables declaration//GEN-END:variables
 private void borrarFilas(){
        int indice = modelo.getRowCount() -1;
        
        for (int i = indice;i>=0;i--){
            modelo.removeRow(i);
        }
 }
}

